// Generated by gencpp from file tutorial/assignmentRequest.msg
// DO NOT EDIT!


#ifndef TUTORIAL_MESSAGE_ASSIGNMENTREQUEST_H
#define TUTORIAL_MESSAGE_ASSIGNMENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tutorial
{
template <class ContainerAllocator>
struct assignmentRequest_
{
  typedef assignmentRequest_<ContainerAllocator> Type;

  assignmentRequest_()
    : tag1_id(0)
    , tag2_id(0)  {
    }
  assignmentRequest_(const ContainerAllocator& _alloc)
    : tag1_id(0)
    , tag2_id(0)  {
  (void)_alloc;
    }



   typedef int64_t _tag1_id_type;
  _tag1_id_type tag1_id;

   typedef int64_t _tag2_id_type;
  _tag2_id_type tag2_id;





  typedef boost::shared_ptr< ::tutorial::assignmentRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial::assignmentRequest_<ContainerAllocator> const> ConstPtr;

}; // struct assignmentRequest_

typedef ::tutorial::assignmentRequest_<std::allocator<void> > assignmentRequest;

typedef boost::shared_ptr< ::tutorial::assignmentRequest > assignmentRequestPtr;
typedef boost::shared_ptr< ::tutorial::assignmentRequest const> assignmentRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial::assignmentRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial::assignmentRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tutorial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tutorial::assignmentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial::assignmentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial::assignmentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial::assignmentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial::assignmentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial::assignmentRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial::assignmentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f286f46d5c435878fb57d59632e4582f";
  }

  static const char* value(const ::tutorial::assignmentRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf286f46d5c435878ULL;
  static const uint64_t static_value2 = 0xfb57d59632e4582fULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial::assignmentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial/assignmentRequest";
  }

  static const char* value(const ::tutorial::assignmentRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial::assignmentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 tag1_id\n\
int64 tag2_id\n\
";
  }

  static const char* value(const ::tutorial::assignmentRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial::assignmentRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tag1_id);
      stream.next(m.tag2_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct assignmentRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial::assignmentRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial::assignmentRequest_<ContainerAllocator>& v)
  {
    s << indent << "tag1_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.tag1_id);
    s << indent << "tag2_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.tag2_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL_MESSAGE_ASSIGNMENTREQUEST_H
